services:
  tcp_lab:
    build: .
    container_name: tcp
    volumes:
      - .:/workspace
    ports:
      - "1234:1234"
    cap_add:
      - NET_ADMIN
      - NET_RAW
    security_opt:
      - seccomp:unconfined
    command: >
      bash -c "make clean && make && echo '[+] Build successful.' && iptables -A OUTPUT -p tcp --tcp-flags RST RST -s 172.16.241.1 -j DROP && echo '[+] Kernel RST suppressed.' && ./xtcp"
